version: '3.8'

services:

  app:
    build: .
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html   # para desarrollo en tiempo real
    depends_on:
      - db
    networks:
      - red_proyecto

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_biblioteca
    volumes:
      - db_data:/var/lib/mysql          # persistencia de datos
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    networks:
      - red_proyecto

volumes:
  db_data:   # volumen nombrado para persistencia

networks:
  red_proyecto:
    driver: bridge